### ISSUE TITLE
Spaces Allowed

### ISSUE THREAD

**Issue by pushp0124** [satyen95/iOS-OTPField#2]
In the text fields spaces are allowed and checkForValidity() is returning true for them. Making 6 textfields as non optional. I changed the if condition in checkForValidity() function and it's working fine. 

private final func checkForValidity(){
        for fields in textFieldsCollection{
            if (fields.text?.trimmingCharacters(in: CharacterSet.whitespaces) == ""){
                delegate?.didChangeValidity(isValid: false)
                return
            }
        }
        delegate?.didChangeValidity(isValid: true)
    }
This repo is really nice. Thanks for sharing this with us.

**Comment by satyen95** [comment]
The issue has been fixed
