### ISSUE TITLE
One time code is putting the first number in the third textField 

### ISSUE THREAD

**Issue by acarolsf** [satyen95/iOS-OTPField#3]
When I send the code and I choose to click on the message to set the OTP automatically, the first two textfields get empty... But thanks for the code, is very helpful.

**Comment by emelyanovkirill** [comment]
Now, when clicking on "1234", the `shouldChangeCharactersIn` method receives 6 events: "", "", "1", "2", "3", "4" instead of "1234", so the empty lines should be omitted, but in this case `beginFirstResponder()` in this method won't work if clean text was received :(

**Comment by satyen95** [comment]
Okay, I'll be looking into it

**Comment by satyen95** [comment]
The issue has been fixed

**Comment by acarolsf** [comment]
I solved using other way. 
First, I call an extension of String and I declared a variable to check if is an integer number.

`extension String {
     var isInt: Bool {
        return Int(self) != nil
    }
}`

Then, inside the `shouldChangeCharactersIn`, I put the follow code:

`if !string.isInt {
     return true
 }`

But yours is more simple. Thank you!
